"""Add table invalidated_tokens

Revision ID: 113b20611a9d
Revises: 2564e8cf4dce
Create Date: 2025-06-02 22:05:44.904556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113b20611a9d'
down_revision: Union[str, None] = '2564e8cf4dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invalidated_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invalidated_tokens_id'), 'invalidated_tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invalidated_tokens_id'), table_name='invalidated_tokens')
    op.drop_table('invalidated_tokens')
    # ### end Alembic commands ###
