"""Create database's tables

Revision ID: 2564e8cf4dce
Revises: 
Create Date: 2025-06-02 21:17:02.953649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2564e8cf4dce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_info_email'), 'users_info', ['email'], unique=True)
    op.create_index(op.f('ix_users_info_id'), 'users_info', ['id'], unique=False)
    op.create_table('users_authentication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_info_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_info_id'], ['users_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_authentication_id'), 'users_authentication', ['id'], unique=False)
    op.create_index(op.f('ix_users_authentication_username'), 'users_authentication', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_authentication_username'), table_name='users_authentication')
    op.drop_index(op.f('ix_users_authentication_id'), table_name='users_authentication')
    op.drop_table('users_authentication')
    op.drop_index(op.f('ix_users_info_id'), table_name='users_info')
    op.drop_index(op.f('ix_users_info_email'), table_name='users_info')
    op.drop_table('users_info')
    # ### end Alembic commands ###
