"""Add phone number and avatar for UserInfo table

Revision ID: 753149e73f6e
Revises: 113b20611a9d
Create Date: 2025-06-03 14:54:24.254728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '753149e73f6e'
down_revision: Union[str, None] = '113b20611a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_info', sa.Column('phone_number', sa.String(length=12), nullable=False))
    op.add_column('users_info', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_info', 'avatar')
    op.drop_column('users_info', 'phone_number')
    # ### end Alembic commands ###
