"""create tables

Revision ID: cd07a4bb4679
Revises: 
Create Date: 2025-06-11 23:34:19.710851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd07a4bb4679'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invalidated_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_info_email'), 'users_info', ['email'], unique=True)
    op.create_index(op.f('ix_users_info_phone'), 'users_info', ['phone'], unique=False)
    op.create_table('users_authentication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_info_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_info_id'], ['users_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_authentication_user_info_id'), 'users_authentication', ['user_info_id'], unique=False)
    op.create_index(op.f('ix_users_authentication_username'), 'users_authentication', ['username'], unique=True)
    op.create_table('user_role',
    sa.Column('user_authentication_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_authentication_id'], ['users_authentication.id'], ),
    sa.PrimaryKeyConstraint('user_authentication_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_index(op.f('ix_users_authentication_username'), table_name='users_authentication')
    op.drop_index(op.f('ix_users_authentication_user_info_id'), table_name='users_authentication')
    op.drop_table('users_authentication')
    op.drop_index(op.f('ix_users_info_phone'), table_name='users_info')
    op.drop_index(op.f('ix_users_info_email'), table_name='users_info')
    op.drop_table('users_info')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('invalidated_tokens')
    # ### end Alembic commands ###
